using Godot;
using System;

/// <summary>
/// How well an encounter went. Drives both the payout band and the
/// presentation — the cloud VFX reads this to pick its colour, density and
/// duration, so one parameterized effect covers every outcome.
/// </summary>
public enum EncounterQuality
{
    /// <summary>Something went badly wrong. Incident likely.</summary>
    Disastrous,

    /// <summary>Below what the client paid for. Discount demanded, reputation dented.</summary>
    Poor,

    /// <summary>Fine. The expected transaction, at the expected price.</summary>
    Adequate,

    /// <summary>Better than expected. Tips, and a decent chance they come back.</summary>
    Good,

    /// <summary>Memorable. Large tip, likely a Regular, possibly useful intel.</summary>
    Exceptional
}

/// <summary>What an incident during an encounter actually was.</summary>
public enum EncounterIncident
{
    None,

    /// <summary>The client became abusive. Trauma to staff, reputation risk.</summary>
    ClientAbuse,

    /// <summary>A dispute over the bill. Revenue lost.</summary>
    PaymentDispute,

    /// <summary>Loud enough to be noticed from outside. Heat.</summary>
    NoiseComplaint,

    /// <summary>The staff member could not go through with it. No revenue, heavy stress.</summary>
    StaffBreakdown
}

/// <summary>
/// The computed result of one encounter. The encounter itself is a black box
/// in presentation — nothing is depicted, so everything that matters is
/// decided here, from odds the player set during Preparation.
/// </summary>
public class EncounterOutcome
{
    public EncounterQuality Quality { get; set; }
    public EncounterIncident Incident { get; set; } = EncounterIncident.None;

    /// <summary>Cash actually collected.</summary>
    public double Payment { get; set; }

    /// <summary>Raw score 0–100 before banding. Useful for tuning and debug overlays.</summary>
    public float Score { get; set; }

    /// <summary>Stress the staff member should take on.</summary>
    public float StaffStressDelta { get; set; }

    /// <summary>Trauma the staff member should take on. Only non-zero on bad incidents.</summary>
    public float StaffTraumaDelta { get; set; }

    /// <summary>Reputation change for the house.</summary>
    public float ReputationDelta { get; set; }

    /// <summary>Heat generated by this encounter specifically.</summary>
    public float HeatDelta { get; set; }

    /// <summary>Whether the client intends to return.</summary>
    public bool BecameRegular { get; set; }

    /// <summary>Whether an Informant picked something up.</summary>
    public bool IntelOpportunity { get; set; }

    /// <summary>Short player-facing line for the Ledger recap.</summary>
    public string Narrative { get; set; } = "";

    public override string ToString() =>
        $"{Quality} (score {Score:F0}) ${Payment:F0}" +
        $"{(Incident != EncounterIncident.None ? $" — {Incident}" : "")}";
}

/// <summary>
/// Resolves a single encounter into an <see cref="EncounterOutcome"/>.
///
/// Deliberately pure: it takes everything it needs as arguments, touches no
/// singletons, and mutates nothing. <see cref="NightDirector"/> applies the
/// result. That keeps the scoring formula testable in isolation, which
/// matters because it is the main dial for game balance.
///
/// Design note — the presentation choice drives the design here. Because the
/// encounter is shown only as an abstract cloud, the player's whole
/// contribution happens *before* it: which room, furnished how, staffed by
/// whom. This function is the resolve of that setup, and adding a new outcome
/// costs no animation work at all.
/// </summary>
public static class EncounterResolver
{
    // ── Scoring weights ────────────────────────────────────────────────

    // Tuning intent: a par house (Appointment meeting expectation, average
    // staff, no style match, rested) should land Adequate. Deliberate play —
    // a well-appointed room in a style the client wanted, worked by strong
    // rested staff — should reach Good and occasionally Exceptional. Neglect
    // should fall to Poor and Disastrous.
    //
    // The first pass weighted the player's own levers too weakly: across 20
    // encounters nothing ever cleared Good, because the modifiers could not
    // move the score far enough from base. These weights are roughly doubled
    // so that what the player controls actually decides the outcome.

    /// <summary>Score everyone starts from before modifiers.</summary>
    public const float BaseScore = 47f;

    /// <summary>Score per point the room's Appointment beats the client's expectation.</summary>
    public const float AppointmentWeight = 0.55f;

    /// <summary>Score per point of staff Charisma above the 50 midpoint.</summary>
    public const float CharismaWeight = 0.40f;

    /// <summary>Bonus when the room's dominant style matches what the client wanted.</summary>
    public const float StyleMatchBonus = 14f;

    /// <summary>Score lost per point of staff Stress.</summary>
    public const float StressPenalty = 0.22f;

    /// <summary>Score lost per point of staff Trauma.</summary>
    public const float TraumaPenalty = 0.07f;

    /// <summary>Bonus for a Hostess working the encounter.</summary>
    public const float HostessBonus = 10f;

    /// <summary>
    /// Random swing applied to every encounter, plus or minus. Kept modest so
    /// preparation reads as the dominant factor rather than luck.
    /// </summary>
    public const float RandomSwing = 7f;

    // ── Quality bands ──────────────────────────────────────────────────

    // Positioned so a well-appointed room alone lands Adequate, and reaching
    // Good takes a second deliberate factor on top — a style match, strong
    // staff, or a specialization. An earlier pass put Good at 58, which the
    // Appointment term cleared on its own and made Good the modal band.
    public const float ExceptionalThreshold = 82f;
    public const float GoodThreshold = 62f;
    public const float AdequateThreshold = 40f;
    public const float PoorThreshold = 24f;

    /// <summary>
    /// Resolve one encounter.
    /// </summary>
    /// <param name="appointment">Room Appointment score, 0–100.</param>
    /// <param name="expectedAppointment">What the client considered par.</param>
    /// <param name="styleMatched">Whether the room's dominant style is the client's preference.</param>
    /// <param name="roomDiscretion">Effective discretion of the room, 0–100.</param>
    /// <param name="staff">Who worked it. Null is treated as an unstaffed room.</param>
    /// <param name="agreedPrice">Price already settled, before quality adjustment.</param>
    /// <param name="spendMultiplier">City-wide client spend multiplier from the macro economy.</param>
    /// <param name="rng">Caller-supplied RNG so runs can be seeded and reproduced.</param>
    public static EncounterOutcome Resolve(
        float appointment,
        float expectedAppointment,
        bool styleMatched,
        float roomDiscretion,
        StaffMember staff,
        double agreedPrice,
        float spendMultiplier,
        RandomNumberGenerator rng)
    {
        var outcome = new EncounterOutcome();

        // ── Score ──────────────────────────────────────────────────────
        float score = BaseScore;
        score += (appointment - expectedAppointment) * AppointmentWeight;

        if (staff != null)
        {
            score += (staff.Charisma - 50f) * CharismaWeight;
            score -= staff.Stress * StressPenalty;
            score -= staff.Trauma * TraumaPenalty;

            if (staff.Specialization == StaffSpecialization.Hostess)
                score += HostessBonus;
        }
        else
        {
            // An unattended room is a bad experience regardless of decor.
            score -= 25f;
        }

        if (styleMatched) score += StyleMatchBonus;

        score += (rng.Randf() * 2f - 1f) * RandomSwing;
        score = Mathf.Clamp(score, 0f, 100f);

        outcome.Score = score;
        outcome.Quality = BandFor(score);

        // ── Payment ────────────────────────────────────────────────────
        // Quality moves the take around the agreed price: a poor night gets
        // haggled down at the door, an exceptional one gets tipped.
        double qualityMultiplier = outcome.Quality switch
        {
            EncounterQuality.Exceptional => 1.35,
            EncounterQuality.Good => 1.12,
            EncounterQuality.Adequate => 1.00,
            EncounterQuality.Poor => 0.72,
            _ => 0.40
        };

        outcome.Payment = Math.Round(
            Math.Max(0.0, agreedPrice * qualityMultiplier * Mathf.Max(0.1f, spendMultiplier)), 2);

        // ── Staff cost ─────────────────────────────────────────────────
        if (staff != null)
        {
            // Low-discretion rooms are more exposing and therefore harder work.
            float roomRisk = 1.5f - (Mathf.Clamp(roomDiscretion, 0f, 100f) / 100f);
            float mitigation = 1.0f - (staff.Discretion / 200f);

            // Tuned against nightly recovery: four Adequate encounters should
            // cost slightly less than a night's rest restores, so a normal
            // shift is sustainable and only a bad or busy one accumulates.
            float baseCost = outcome.Quality switch
            {
                EncounterQuality.Exceptional => 3f,
                EncounterQuality.Good => 4f,
                EncounterQuality.Adequate => 5.5f,
                EncounterQuality.Poor => 8f,
                _ => 13f
            };

            outcome.StaffStressDelta = baseCost * roomRisk * mitigation;
        }

        // ── Consequences ───────────────────────────────────────────────
        ApplyQualityConsequences(outcome, staff, roomDiscretion, rng);

        return outcome;
    }

    private static EncounterQuality BandFor(float score) => score switch
    {
        >= ExceptionalThreshold => EncounterQuality.Exceptional,
        >= GoodThreshold => EncounterQuality.Good,
        >= AdequateThreshold => EncounterQuality.Adequate,
        >= PoorThreshold => EncounterQuality.Poor,
        _ => EncounterQuality.Disastrous
    };

    /// <summary>
    /// Reputation, heat, incidents and follow-on hooks. Split out so the
    /// scoring above stays readable and independently testable.
    /// </summary>
    private static void ApplyQualityConsequences(
        EncounterOutcome outcome, StaffMember staff, float roomDiscretion, RandomNumberGenerator rng)
    {
        switch (outcome.Quality)
        {
            case EncounterQuality.Exceptional:
                outcome.ReputationDelta = 1.5f;
                outcome.BecameRegular = rng.Randf() < 0.55f;
                outcome.IntelOpportunity =
                    staff?.Specialization == StaffSpecialization.Informant && rng.Randf() < 0.6f;
                outcome.Narrative = "Left visibly delighted, and tipped for it.";
                break;

            case EncounterQuality.Good:
                outcome.ReputationDelta = 0.6f;
                outcome.BecameRegular = rng.Randf() < 0.25f;
                outcome.IntelOpportunity =
                    staff?.Specialization == StaffSpecialization.Informant && rng.Randf() < 0.3f;
                outcome.Narrative = "A good night. They'll speak well of the house.";
                break;

            case EncounterQuality.Adequate:
                outcome.Narrative = "Unremarkable. Paid and left.";
                break;

            case EncounterQuality.Poor:
                // Kept small relative to the Good/Exceptional gains. A steeper
                // penalty here compounds into a reputation spiral: fewer
                // arrivals, fewer chances to recover, fewer arrivals again.
                outcome.ReputationDelta = -0.6f;
                outcome.Narrative = "Grumbled about the room on the way out.";

                if (rng.Randf() < 0.25f)
                {
                    outcome.Incident = EncounterIncident.PaymentDispute;
                    outcome.Payment *= 0.5;
                    outcome.Narrative = "Disputed the bill and paid half.";
                }
                break;

            case EncounterQuality.Disastrous:
                outcome.ReputationDelta = -3f;
                outcome.Incident = RollIncident(staff, rng);

                switch (outcome.Incident)
                {
                    case EncounterIncident.ClientAbuse:
                        outcome.StaffTraumaDelta = 8f + rng.Randf() * 10f;
                        outcome.StaffStressDelta += 12f;
                        outcome.ReputationDelta -= 2f;
                        outcome.Narrative = "The client turned. It should not have gone that far.";
                        break;

                    case EncounterIncident.StaffBreakdown:
                        outcome.Payment = 0;
                        outcome.StaffStressDelta += 15f;
                        outcome.StaffTraumaDelta = 5f;
                        outcome.Narrative = "She couldn't go through with it. The client was sent away.";
                        break;

                    case EncounterIncident.NoiseComplaint:
                        // Quiet rooms make this far less likely, which is what
                        // soundproofing spend is actually buying.
                        outcome.HeatDelta = 3f + (1f - roomDiscretion / 100f) * 5f;
                        outcome.Narrative = "Loud enough that the street heard it.";
                        break;

                    default:
                        outcome.Incident = EncounterIncident.PaymentDispute;
                        outcome.Payment = 0;
                        outcome.Narrative = "Walked out without paying.";
                        break;
                }
                break;
        }
    }

    /// <summary>
    /// Pick which way a disastrous encounter went wrong. A staff member who
    /// is already close to breaking is far likelier to be the failure point
    /// than the client — which is the feedback loop that makes running people
    /// into the ground expensive.
    /// </summary>
    private static EncounterIncident RollIncident(StaffMember staff, RandomNumberGenerator rng)
    {
        float breakdownChance = staff == null
            ? 0f
            : Mathf.Clamp((staff.Stress - 50f) / 100f, 0f, 0.45f);

        float roll = rng.Randf();

        if (roll < breakdownChance) return EncounterIncident.StaffBreakdown;
        if (roll < breakdownChance + 0.35f) return EncounterIncident.ClientAbuse;
        if (roll < breakdownChance + 0.60f) return EncounterIncident.NoiseComplaint;

        return EncounterIncident.PaymentDispute;
    }

    /// <summary>
    /// Presentation parameters for the cloud VFX. Returned as plain values so
    /// the effect scene stays a single parameterized node rather than one
    /// animation per outcome.
    /// </summary>
    public static (Color Tint, float Density, float DurationScale) GetVfxParameters(EncounterQuality quality) =>
        quality switch
        {
            EncounterQuality.Exceptional => (new Color(1.0f, 0.84f, 0.45f), 1.0f, 1.25f),
            EncounterQuality.Good        => (new Color(0.85f, 0.75f, 0.60f), 0.8f, 1.10f),
            EncounterQuality.Adequate    => (new Color(0.70f, 0.70f, 0.72f), 0.6f, 1.00f),
            EncounterQuality.Poor        => (new Color(0.55f, 0.52f, 0.55f), 0.45f, 0.85f),
            _                            => (new Color(0.70f, 0.30f, 0.28f), 0.35f, 0.60f)
        };
}
