using Godot;
using System;
using System.Collections.Generic;
using System.Linq;

/// <summary>
/// How a candidate is being sourced. Each channel trades cost, quality,
/// speed, and moral consequence differently — this is the primary reason two
/// campaigns diverge, because the Panderer's Code branch makes different
/// channels viable.
/// </summary>
public enum RecruitmentChannel
{
    /// <summary>Discreet advertisement. Cheap, slow, weak candidates. Always available.</summary>
    OpenCall,

    /// <summary>Bought away from a rival house. Expensive, strong, and the rival remembers.</summary>
    Poaching,

    /// <summary>Contract acquired along with their debt. Cheap, traumatized, cannot quit.</summary>
    DebtAcquisition,

    /// <summary>Sought the house out on its reputation. Free and strong, but gated behind Reputation.</summary>
    ReputationWalkIn,

    /// <summary>Pulled out of a worse house. Traumatized but deeply loyal.</summary>
    Rescue
}

/// <summary>
/// A prospective hire, plus the terms attached to taking them on.
/// The <see cref="Staff"/> instance is fully formed — hiring moves it onto
/// the roster unchanged, so what the player is shown is what they get.
/// </summary>
public class Candidate
{
    public StaffMember Staff { get; set; }
    public RecruitmentChannel Channel { get; set; }

    /// <summary>Up-front cash cost to hire.</summary>
    public double HireCost { get; set; }

    /// <summary>Player-facing summary of the non-cash cost of this channel.</summary>
    public string ConsequenceNote { get; set; } = "";

    /// <summary>Day this candidate becomes unavailable.</summary>
    public int ExpiresOnDay { get; set; }

    public override string ToString() =>
        $"{Staff?.StaffName} via {Channel} — ${HireCost:F0}. {ConsequenceNote}";
}

/// <summary>
/// Staff acquisition. Generates candidates through five channels and applies
/// each channel's consequences on hire.
///
/// There was previously no hiring path at all — no candidate pool, no cost,
/// no <c>new StaffMember</c> anywhere in the codebase — so the roster could
/// only ever be empty. This is that missing input layer.
///
/// Registered by name in the scene tree; found via FindChild by other systems.
/// </summary>
public partial class RecruitmentService : Node, ISaveableSystem
{
    // ── Signals ────────────────────────────────────────────────────────

    /// <summary>Fired when a channel produces new candidates.</summary>
    [Signal]
    public delegate void OnCandidatesAvailableEventHandler(int channel, int count);

    /// <summary>Fired when a hire completes.</summary>
    [Signal]
    public delegate void OnCandidateHiredEventHandler(string staffId, string staffName, int channel);

    /// <summary>Fired when a hire is refused, with a player-facing reason.</summary>
    [Signal]
    public delegate void OnHireRejectedEventHandler(string reason);

    /// <summary>Fired when an open call is posted and begins its wait.</summary>
    [Signal]
    public delegate void OnOpenCallPostedEventHandler(int arrivesOnDay, double cost);

    // ── Configuration ──────────────────────────────────────────────────

    /// <summary>Cost of posting a discreet advertisement.</summary>
    [Export] public double OpenCallPostingFee { get; set; } = 200.0;

    /// <summary>Reputation required before talent approaches the house unprompted.</summary>
    [Export] public float WalkInReputationThreshold { get; set; } = 65.0f;

    /// <summary>Nights a candidate remains available before moving on.</summary>
    [Export] public int CandidateShelfLifeDays { get; set; } = 6;

    /// <summary>Heat generated by taking on a debt contract.</summary>
    [Export] public float DebtAcquisitionHeat { get; set; } = 8.0f;

    /// <summary>Public sentiment lost by taking on a debt contract.</summary>
    [Export] public float DebtAcquisitionSentimentCost { get; set; } = 10.0f;

    /// <summary>Heat generated by extracting someone from a rival house.</summary>
    [Export] public float RescueHeat { get; set; } = 5.0f;

    /// <summary>Aggression a rival syndicate gains when poached from.</summary>
    [Export] public float PoachingAggressionPenalty { get; set; } = 12.0f;

    // ── State ──────────────────────────────────────────────────────────

    private readonly List<Candidate> _candidates = new();
    private readonly RandomNumberGenerator _rng = new();

    private int _openCallArrivalDay = -1;
    private int _lastWalkInCheckDay = -1;

    /// <summary>Candidates currently available to hire.</summary>
    public IReadOnlyList<Candidate> Candidates => _candidates;

    /// <summary>Whether an open call is posted and still pending.</summary>
    public bool OpenCallPending => _openCallArrivalDay >= 0;

    // ── Name generation ────────────────────────────────────────────────

    private static readonly string[] GivenNames =
    {
        "Mireille", "Coralie", "Sable", "Odette", "Vesna", "Talia", "Isolde",
        "Rosalind", "Junia", "Cassia", "Emeline", "Zora", "Nadia", "Perpetua",
        "Lucia", "Anouk", "Thea", "Marguerite", "Sonja", "Elke", "Ottilie"
    };

    private static readonly string[] Surnames =
    {
        "Vance", "Ashworth", "Rousseau", "Kovač", "Lindqvist", "Marchetti",
        "Delacroix", "Sørensen", "Baranov", "Ferreira", "Halloran", "Ó Briain",
        "Weiss", "Tanaka", "Okonkwo", "Varga", "Novak", "Aguilar"
    };

    private static readonly string[] Roles =
    {
        "Attendant", "Hostess", "Companion", "Receptionist", "Concierge"
    };

    // ── Lifecycle ──────────────────────────────────────────────────────

    public override void _Ready()
    {
        WorldRandom.Seed(_rng, nameof(RecruitmentService));

        if (GameStateManager.Instance != null)
            GameStateManager.Instance.OnDailyTick += OnDailyTick;

        GD.Print("[Recruitment] Initialized.");
    }

    public override void _ExitTree()
    {
        if (GameStateManager.Instance != null)
            GameStateManager.Instance.OnDailyTick -= OnDailyTick;
    }

    private void OnDailyTick(double cash, float reputation, float heat, float sentiment)
    {
        var day = GameStateManager.Instance?.DayCount ?? 0;

        ExpireStaleCandidates(day);
        ResolveOpenCall(day);
        CheckForWalkIn(day, reputation);
    }

    // ── Channel: Open Call ─────────────────────────────────────────────

    /// <summary>
    /// Post a discreet advertisement. Costs a small fee up front and takes
    /// 2–4 nights to produce two or three unremarkable candidates.
    /// </summary>
    public bool PostOpenCall()
    {
        if (OpenCallPending)
        {
            EmitSignal(SignalName.OnHireRejected, "An open call is already posted.");
            return false;
        }

        var gsm = GameStateManager.Instance;
        if (gsm == null || gsm.Cash < OpenCallPostingFee)
        {
            EmitSignal(SignalName.OnHireRejected, $"Cannot afford the ${OpenCallPostingFee:F0} posting fee.");
            return false;
        }

        ChargeExpense(OpenCallPostingFee, "Open call advertisement");

        var day = gsm.DayCount;
        _openCallArrivalDay = day + 2 + (int)(_rng.Randi() % 3u);

        EmitSignal(SignalName.OnOpenCallPosted, _openCallArrivalDay, OpenCallPostingFee);
        GD.Print($"[Recruitment] Open call posted. Responses expected day {_openCallArrivalDay}.");
        return true;
    }

    private void ResolveOpenCall(int day)
    {
        if (_openCallArrivalDay < 0 || day < _openCallArrivalDay) return;

        _openCallArrivalDay = -1;

        var count = 2 + (int)(_rng.Randi() % 2u);
        for (var i = 0; i < count; i++)
            _candidates.Add(BuildCandidate(RecruitmentChannel.OpenCall, day));

        EmitSignal(SignalName.OnCandidatesAvailable, (int)RecruitmentChannel.OpenCall, count);
        GD.Print($"[Recruitment] Open call produced {count} candidates.");
    }

    // ── Channel: Reputation Walk-in ────────────────────────────────────

    /// <summary>
    /// Above the reputation threshold, talent occasionally presents itself
    /// unprompted and for free. This is what makes Reputation a currency
    /// rather than only a footfall multiplier.
    /// </summary>
    private void CheckForWalkIn(int day, float reputation)
    {
        if (reputation < WalkInReputationThreshold) return;
        if (day == _lastWalkInCheckDay) return;

        _lastWalkInCheckDay = day;

        // Scales from ~2% at the threshold to ~10% at full reputation.
        var over = (reputation - WalkInReputationThreshold) / Mathf.Max(1f, 100f - WalkInReputationThreshold);
        var chance = 0.02f + over * 0.08f;

        if (_rng.Randf() >= chance) return;

        _candidates.Add(BuildCandidate(RecruitmentChannel.ReputationWalkIn, day));

        EmitSignal(SignalName.OnCandidatesAvailable, (int)RecruitmentChannel.ReputationWalkIn, 1);
        GD.Print("[Recruitment] Someone presented themselves at the door on reputation alone.");
    }

    // ── Channels: on-demand ────────────────────────────────────────────

    /// <summary>
    /// Generate an on-demand offer for a channel that does not require
    /// waiting: poaching, debt acquisition, or a rescue. Returns null if the
    /// channel is unavailable right now.
    /// </summary>
    public Candidate SolicitOffer(RecruitmentChannel channel)
    {
        if (channel is RecruitmentChannel.OpenCall or RecruitmentChannel.ReputationWalkIn)
        {
            EmitSignal(SignalName.OnHireRejected, $"{channel} cannot be solicited on demand.");
            return null;
        }

        var day = GameStateManager.Instance?.DayCount ?? 0;
        var candidate = BuildCandidate(channel, day);

        _candidates.Add(candidate);
        EmitSignal(SignalName.OnCandidatesAvailable, (int)channel, 1);

        return candidate;
    }

    // ── Hiring ─────────────────────────────────────────────────────────

    /// <summary>
    /// Take a candidate onto the roster, paying the cash cost and applying
    /// the channel's consequences.
    /// </summary>
    /// <returns>True if hired.</returns>
    public bool Hire(Candidate candidate)
    {
        if (candidate?.Staff == null)
        {
            EmitSignal(SignalName.OnHireRejected, "No candidate selected.");
            return false;
        }

        if (!_candidates.Contains(candidate))
        {
            EmitSignal(SignalName.OnHireRejected, "That candidate is no longer available.");
            return false;
        }

        var roster = StaffRoster.Instance;
        if (roster == null)
        {
            EmitSignal(SignalName.OnHireRejected, "No roster available.");
            return false;
        }

        if (!roster.HasVacancy)
        {
            EmitSignal(SignalName.OnHireRejected, $"The house is full ({roster.Count}/{roster.RosterCap}).");
            return false;
        }

        var gsm = GameStateManager.Instance;
        if (gsm == null || gsm.Cash < candidate.HireCost)
        {
            EmitSignal(SignalName.OnHireRejected, $"Cannot afford ${candidate.HireCost:F0}.");
            return false;
        }

        // Add to the roster BEFORE charging. The cash and vacancy gates above
        // have already passed, so if Add still refuses (a duplicate Id, say)
        // the player must not be left paying for a hire that never happened.
        if (!roster.Add(candidate.Staff))
        {
            EmitSignal(SignalName.OnHireRejected, "The roster refused the hire.");
            return false;
        }

        if (candidate.HireCost > 0)
            ChargeExpense(candidate.HireCost, $"Hired {candidate.Staff.StaffName} ({candidate.Channel})");

        _candidates.Remove(candidate);
        ApplyChannelConsequences(candidate);

        EmitSignal(SignalName.OnCandidateHired,
            candidate.Staff.Id, candidate.Staff.StaffName, (int)candidate.Channel);

        GD.Print($"[Recruitment] Hired {candidate.Staff.StaffName} via {candidate.Channel} " +
                 $"for ${candidate.HireCost:F0}.");
        return true;
    }

    /// <summary>
    /// Apply the non-cash price of a channel. This is where the moral economy
    /// of the game actually lives.
    /// </summary>
    private void ApplyChannelConsequences(Candidate candidate)
    {
        var gsm = GameStateManager.Instance;

        switch (candidate.Channel)
        {
            case RecruitmentChannel.Poaching:
                // The rival remembers being robbed.
                var syndicates = GetTree()?.Root?.FindChild("SyndicateRivalAI", true, false) as SyndicateRivalAI;
                var faction = syndicates?.GetSyndicate(candidate.Staff.AssociatedFaction);
                if (faction != null)
                {
                    faction.Aggression = Mathf.Clamp(faction.Aggression + PoachingAggressionPenalty, 0f, 100f);
                    faction.Respect = Mathf.Clamp(faction.Respect - 8f, 0f, 100f);
                    GD.Print($"[Recruitment] {faction.Name} is aggrieved — aggression now {faction.Aggression:F0}.");
                }
                break;

            case RecruitmentChannel.DebtAcquisition:
                if (gsm != null)
                {
                    gsm.Heat += DebtAcquisitionHeat;
                    gsm.PublicSentiment -= DebtAcquisitionSentimentCost;
                }
                break;

            case RecruitmentChannel.Rescue:
                if (gsm != null) gsm.Heat += RescueHeat;
                break;
        }
    }

    // ── Candidate generation ───────────────────────────────────────────

    /// <summary>
    /// Build a candidate for a channel. The per-channel spread is the design:
    /// exploitation channels are cheap and immediately capable but start with
    /// almost no loyalty and heavy trauma, while the slow channels cost more
    /// and arrive weaker but durable.
    /// </summary>
    private Candidate BuildCandidate(RecruitmentChannel channel, int day)
    {
        var staff = new StaffMember
        {
            StaffName = GenerateName(),
            Role = Roles[(int)(_rng.Randi() % (uint)Roles.Length)],
            Ambition = RollAmbition(channel),
            Origin = ChannelToOrigin(channel)
        };

        double cost;
        string note;

        switch (channel)
        {
            case RecruitmentChannel.OpenCall:
                RollStats(staff, 20f, 45f);
                staff.RestoreLoyalty(50f);
                staff.Salary = 150 + _rng.Randf() * 100;
                cost = 0; // The posting fee was already paid.
                note = "Unremarkable, but owes the house nothing.";
                break;

            case RecruitmentChannel.Poaching:
                RollStats(staff, 55f, 80f);
                staff.RestoreLoyalty(25f);
                staff.Trauma = _rng.Randf() * 15f;
                staff.Salary = 350 + _rng.Randf() * 200;
                staff.AssociatedFaction = PickRivalFaction();
                cost = 1500 + _rng.Randf() * 1500;
                note = $"Taken from {staff.AssociatedFaction}. They will not forget it.";
                break;

            case RecruitmentChannel.DebtAcquisition:
                RollStats(staff, 25f, 60f);
                staff.RestoreLoyalty(10f);
                staff.Trauma = 40f + _rng.Randf() * 30f;
                staff.Satisfaction = 35f;
                staff.Salary = 80 + _rng.Randf() * 60;
                staff.ContractDebt = 3000 + _rng.Randf() * 3000;
                cost = 400 + _rng.Randf() * 200;
                note = $"Bound by ${staff.ContractDebt:F0} of debt. Cannot leave. The street will notice.";
                break;

            case RecruitmentChannel.ReputationWalkIn:
                RollStats(staff, 50f, 75f);
                staff.RestoreLoyalty(65f);
                staff.Trauma = _rng.Randf() * 10f;
                staff.Salary = 300 + _rng.Randf() * 150;
                cost = 0;
                note = "Came to you. Asks nothing up front.";
                break;

            case RecruitmentChannel.Rescue:
                RollStats(staff, 25f, 50f);
                staff.RestoreLoyalty(85f);
                staff.Trauma = 50f + _rng.Randf() * 30f;
                staff.Satisfaction = 45f;
                staff.Salary = 200 + _rng.Randf() * 100;
                cost = 800 + _rng.Randf() * 400;
                note = "Badly hurt, and will not forget who opened the door.";
                break;

            default:
                RollStats(staff, 20f, 45f);
                cost = 0;
                note = "";
                break;
        }

        return new Candidate
        {
            Staff = staff,
            Channel = channel,
            HireCost = Math.Round(cost),
            ConsequenceNote = note,
            ExpiresOnDay = day + CandidateShelfLifeDays
        };
    }

    private void RollStats(StaffMember staff, float min, float max)
    {
        staff.Charisma = min + _rng.Randf() * (max - min);
        staff.Negotiation = min + _rng.Randf() * (max - min);
        staff.Discretion = min + _rng.Randf() * (max - min);
    }

    /// <summary>
    /// Ambitions are weighted by channel: someone bound by debt overwhelmingly
    /// wants out, and someone taken from a rival is likelier to want revenge.
    /// </summary>
    private StaffAmbition RollAmbition(RecruitmentChannel channel)
    {
        var roll = _rng.Randf();

        return channel switch
        {
            RecruitmentChannel.DebtAcquisition => roll < 0.7f ? StaffAmbition.Freedom : StaffAmbition.Money,
            RecruitmentChannel.Rescue => roll < 0.45f ? StaffAmbition.Freedom
                                       : roll < 0.75f ? StaffAmbition.Status
                                       : StaffAmbition.Revenge,
            RecruitmentChannel.Poaching => roll < 0.4f ? StaffAmbition.Money
                                         : roll < 0.7f ? StaffAmbition.Status
                                         : StaffAmbition.Revenge,
            _ => roll < 0.45f ? StaffAmbition.Money
               : roll < 0.8f ? StaffAmbition.Status
               : StaffAmbition.Freedom
        };
    }

    private static StaffOrigin ChannelToOrigin(RecruitmentChannel channel) => channel switch
    {
        RecruitmentChannel.OpenCall => StaffOrigin.OpenCall,
        RecruitmentChannel.Poaching => StaffOrigin.Poached,
        RecruitmentChannel.DebtAcquisition => StaffOrigin.Debt,
        RecruitmentChannel.ReputationWalkIn => StaffOrigin.WalkIn,
        RecruitmentChannel.Rescue => StaffOrigin.Rescue,
        _ => StaffOrigin.OpenCall
    };

    private string GenerateName()
    {
        var given = GivenNames[(int)(_rng.Randi() % (uint)GivenNames.Length)];
        var surname = Surnames[(int)(_rng.Randi() % (uint)Surnames.Length)];
        return $"{given} {surname}";
    }

    private string PickRivalFaction()
    {
        var syndicates = GetTree()?.Root?.FindChild("SyndicateRivalAI", true, false) as SyndicateRivalAI;
        var factions = syndicates?.Syndicates;

        if (factions == null || factions.Count == 0) return "an unnamed house";

        return factions[(int)(_rng.Randi() % (uint)factions.Count)].Name;
    }

    // ── Upkeep ─────────────────────────────────────────────────────────

    private void ExpireStaleCandidates(int day)
    {
        var expired = _candidates.Where(c => day >= c.ExpiresOnDay).ToList();
        foreach (var candidate in expired)
        {
            _candidates.Remove(candidate);
            GD.Print($"[Recruitment] {candidate.Staff.StaffName} took another offer.");
        }
    }

    /// <summary>
    /// Route spending through the ledger so recruitment shows up in the books,
    /// falling back to a direct cash deduction when no ledger is present.
    /// </summary>
    private void ChargeExpense(double amount, string description)
    {
        var ledger = GetTree()?.Root?.FindChild("FinancialLedger", true, false) as FinancialLedger;

        if (ledger != null)
            ledger.RecordExpense(ExpenseCategory.StaffSalaries, amount, description);
        else if (GameStateManager.Instance != null)
            GameStateManager.Instance.Cash -= amount;
    }

    // ── Persistence ────────────────────────────────────────────────────

    public string SaveKey => "recruitment";

    public System.Text.Json.Nodes.JsonObject CaptureState()
    {
        var candidates = new System.Text.Json.Nodes.JsonArray();

        foreach (var c in _candidates)
        {
            candidates.Add(new System.Text.Json.Nodes.JsonObject
            {
                ["channel"] = c.Channel.ToString(),
                ["hireCost"] = c.HireCost,
                ["note"] = c.ConsequenceNote,
                ["expiresOnDay"] = c.ExpiresOnDay,

                ["name"] = c.Staff.StaffName,
                ["role"] = c.Staff.Role,
                ["salary"] = c.Staff.Salary,
                ["charisma"] = c.Staff.Charisma,
                ["negotiation"] = c.Staff.Negotiation,
                ["discretion"] = c.Staff.Discretion,
                ["trauma"] = c.Staff.Trauma,
                ["satisfaction"] = c.Staff.Satisfaction,
                ["loyalty"] = c.Staff.Loyalty,
                ["ambition"] = c.Staff.Ambition.ToString(),
                ["origin"] = c.Staff.Origin.ToString(),
                ["faction"] = c.Staff.AssociatedFaction,
                ["contractDebt"] = c.Staff.ContractDebt
            });
        }

        return new System.Text.Json.Nodes.JsonObject
        {
            ["candidates"] = candidates,
            ["openCallArrivalDay"] = _openCallArrivalDay,
            ["lastWalkInCheckDay"] = _lastWalkInCheckDay
        };
    }

    public void RestoreState(System.Text.Json.Nodes.JsonObject state)
    {
        if (state == null) return;

        _candidates.Clear();
        _openCallArrivalDay = (int?)state["openCallArrivalDay"] ?? -1;
        _lastWalkInCheckDay = (int?)state["lastWalkInCheckDay"] ?? -1;

        if (state["candidates"] is not System.Text.Json.Nodes.JsonArray candidates) return;

        foreach (var node in candidates)
        {
            if (node is not System.Text.Json.Nodes.JsonObject entry) continue;

            var staff = new StaffMember
            {
                StaffName = (string)entry["name"] ?? "Unnamed",
                Role = (string)entry["role"] ?? "Attendant",
                Salary = (double?)entry["salary"] ?? 200.0,
                Charisma = (float?)entry["charisma"] ?? 30f,
                Negotiation = (float?)entry["negotiation"] ?? 20f,
                Discretion = (float?)entry["discretion"] ?? 40f,
                AssociatedFaction = (string)entry["faction"] ?? "",
                ContractDebt = (double?)entry["contractDebt"] ?? 0.0
            };

            staff.Trauma = (float?)entry["trauma"] ?? 0f;
            staff.Satisfaction = (float?)entry["satisfaction"] ?? 70f;
            staff.RestoreLoyalty((float?)entry["loyalty"] ?? 50f);

            if (Enum.TryParse<StaffAmbition>((string)entry["ambition"], true, out var ambition))
                staff.Ambition = ambition;
            if (Enum.TryParse<StaffOrigin>((string)entry["origin"], true, out var origin))
                staff.Origin = origin;

            Enum.TryParse<RecruitmentChannel>((string)entry["channel"], true, out var channel);

            _candidates.Add(new Candidate
            {
                Staff = staff,
                Channel = channel,
                HireCost = (double?)entry["hireCost"] ?? 0.0,
                ConsequenceNote = (string)entry["note"] ?? "",
                ExpiresOnDay = (int?)entry["expiresOnDay"] ?? 0
            });
        }

        GD.Print($"[Recruitment] Restored {_candidates.Count} candidates.");
    }

    public override string ToString() =>
        $"[Recruitment] {_candidates.Count} candidates" +
        $"{(OpenCallPending ? $", open call lands day {_openCallArrivalDay}" : "")}";
}
