using Godot;
using System;

/// <summary>
/// Active role a staff member has qualified for. Each specialization
/// unlocks an ability and is gated behind an RPG stat threshold.
/// </summary>
public enum StaffSpecialization
{
    /// <summary>No specialization yet. Works generic shifts.</summary>
    None,

    /// <summary>Charisma ≥ 60. Raises satisfaction for every client in the same room.</summary>
    Hostess,

    /// <summary>Negotiation ≥ 60. Better haggling odds; can run two negotiations a night.</summary>
    Negotiator,

    /// <summary>Discretion ≥ 65. Reduces Heat generated by their assigned floor.</summary>
    Fixer,

    /// <summary>Discretion ≥ 55. Gathers client intel for the blackmail network.</summary>
    Informant,

    /// <summary>All three stats ≥ 50. Mentors the roster; slows stress accumulation house-wide.</summary>
    Matron
}

/// <summary>
/// What this staff member personally wants. Progress toward it raises
/// Loyalty; neglecting it erodes Loyalty and eventually triggers exit,
/// betrayal, or union agitation.
/// </summary>
public enum StaffAmbition
{
    /// <summary>Wants earnings. Satisfied by bonuses and high-value clients.</summary>
    Money,

    /// <summary>Wants out. Satisfied by paying down their contract.</summary>
    Freedom,

    /// <summary>Wants to be the house headliner. Satisfied by VIP assignments and training.</summary>
    Status,

    /// <summary>Wants a named rival hurt. Satisfied by acting against that syndicate.</summary>
    Revenge
}

/// <summary>
/// How this staff member was acquired. Sets starting Loyalty and Trauma,
/// and gates certain narrative outcomes.
/// </summary>
public enum StaffOrigin
{
    /// <summary>Answered a discreet advertisement. Neutral start.</summary>
    OpenCall,

    /// <summary>Bought away from a rival house. High stats, low loyalty, creates a grudge.</summary>
    Poached,

    /// <summary>Contract acquired with their debt. Cannot quit; high trauma, minimal loyalty.</summary>
    Debt,

    /// <summary>Sought the house out on reputation alone. High stats and good loyalty.</summary>
    WalkIn,

    /// <summary>Pulled out of a worse house. High trauma, but loyalty starts near maximum.</summary>
    Rescue
}

/// <summary>
/// Represents an employee with RPG-style stats and psychological
/// agency variables. Used by the staff management system to
/// track individual performance and well-being.
///
/// Stats (stable, trained): Charisma, Negotiation, Discretion.
/// Agency (dynamic, per-shift): Stress, Satisfaction, Trauma, Loyalty.
/// Identity: Specialization, Ambition, Origin, Relationships.
///
/// Owned by <see cref="StaffRoster"/>. Saveable as a .tres Resource file.
/// </summary>
[GlobalClass]
public partial class StaffMember : Resource
{
    // ── Signals ────────────────────────────────────────────────────────

    /// <summary>Fired when any RPG stat changes.</summary>
    [Signal]
    public delegate void OnStatChangedEventHandler(
        string statName, float newValue, float delta);

    /// <summary>Fired when any agency variable changes.</summary>
    [Signal]
    public delegate void OnAgencyChangedEventHandler(
        string agencyName, float newValue, float delta);

    /// <summary>Fired when Stress exceeds the burnout threshold (≥ 90).</summary>
    [Signal]
    public delegate void OnBurnoutRiskEventHandler(float stress, float satisfaction);

    /// <summary>Fired when Trauma exceeds the PTSD threshold (≥ 80).</summary>
    [Signal]
    public delegate void OnTraumaThresholdEventHandler(float trauma);

    /// <summary>Fired when Satisfaction drops to zero (quit risk).</summary>
    [Signal]
    public delegate void OnQuitRiskEventHandler(float satisfaction);

    /// <summary>Fired when Loyalty changes.</summary>
    [Signal]
    public delegate void OnLoyaltyChangedEventHandler(float newValue, float delta, string reason);

    /// <summary>Fired when a specialization is unlocked.</summary>
    [Signal]
    public delegate void OnSpecializationUnlockedEventHandler(string staffId, int specialization);

    /// <summary>Fired when ambition progress advances.</summary>
    [Signal]
    public delegate void OnAmbitionProgressedEventHandler(string staffId, int ambition, float progress);

    /// <summary>Fired when an ambition reaches 100 and resolves.</summary>
    [Signal]
    public delegate void OnAmbitionFulfilledEventHandler(string staffId, int ambition);

    /// <summary>
    /// Fired when Loyalty bottoms out. Unlike <see cref="OnQuitRiskEventHandler"/>
    /// (which is about misery), this is about defection — poaching, testimony,
    /// or walking to a rival house.
    /// </summary>
    [Signal]
    public delegate void OnDefectionRiskEventHandler(string staffId, float loyalty);

    // ── Identity ───────────────────────────────────────────────────────

    /// <summary>
    /// Stable unique identifier. Names are display text and may collide or
    /// change; every cross-reference (relationships, save data, assignments)
    /// keys on this instead.
    /// </summary>
    [Export]
    public string Id { get; set; } = Guid.NewGuid().ToString("N")[..12];

    [Export]
    public string StaffName { get; set; } = "Unnamed";

    [Export(PropertyHint.MultilineText)]
    public string Backstory { get; set; } = "";

    [Export]
    public string Role { get; set; } = "Attendant";

    /// <summary>Monthly salary in dollars.</summary>
    [Export]
    public double Salary { get; set; } = 200.0;

    // ── RPG Stats (0–100, trained over time) ───────────────────────────

    private float _charisma = 30f;
    private float _negotiation = 20f;
    private float _discretion = 40f;

    /// <summary>
    /// Charm and social grace. Affects client satisfaction,
    /// tip income, and VIP service quality.
    /// </summary>
    [Export(PropertyHint.Range, "0,100,1")]
    public float Charisma
    {
        get => _charisma;
        set => SetStat(ref _charisma, nameof(Charisma), value);
    }

    /// <summary>
    /// Haggling and deal-making ability. Affects bribe efficiency,
    /// supplier costs, and conflict resolution.
    /// </summary>
    [Export(PropertyHint.Range, "0,100,1")]
    public float Negotiation
    {
        get => _negotiation;
        set => SetStat(ref _negotiation, nameof(Negotiation), value);
    }

    /// <summary>
    /// Ability to keep secrets and avoid detection. Reduces Heat
    /// generation and increases room operation safety.
    /// </summary>
    [Export(PropertyHint.Range, "0,100,1")]
    public float Discretion
    {
        get => _discretion;
        set => SetStat(ref _discretion, nameof(Discretion), value);
    }

    // ── Agency Variables (0–100, dynamic per-shift) ────────────────────

    private float _stress;
    private float _satisfaction = 70f;
    private float _trauma;
    private float _loyalty = 50f;

    /// <summary>
    /// Current stress level. Increases with workload and low-discretion
    /// rooms. Decreases with rest. At ≥ 90, triggers OnBurnoutRisk.
    /// </summary>
    [Export(PropertyHint.Range, "0,100,1")]
    public float Stress
    {
        get => _stress;
        set => SetAgency(ref _stress, nameof(Stress), value, checkBurnout: true);
    }

    /// <summary>
    /// Job satisfaction. Decreases as stress rises. Increases with
    /// bonuses and positive events. At 0, triggers OnQuitRisk.
    /// </summary>
    [Export(PropertyHint.Range, "0,100,1")]
    public float Satisfaction
    {
        get => _satisfaction;
        set => SetAgency(ref _satisfaction, nameof(Satisfaction), value, checkQuit: true);
    }

    /// <summary>
    /// Accumulated psychological trauma. Increases from raids,
    /// violent incidents, and extreme stress events. Reduces
    /// max achievable Satisfaction. At ≥ 80, triggers OnTraumaThreshold.
    /// </summary>
    [Export(PropertyHint.Range, "0,100,1")]
    public float Trauma
    {
        get => _trauma;
        set => SetAgency(ref _trauma, nameof(Trauma), value, checkTrauma: true);
    }

    /// <summary>
    /// Attachment to the house, 0–100. Distinct from Satisfaction:
    /// Satisfaction is how the job feels right now, Loyalty is whether
    /// they would leave, take a rival's offer, or testify. Moves slowly,
    /// driven by ambition progress and how the house treats them.
    /// </summary>
    [Export(PropertyHint.Range, "0,100,1")]
    public float Loyalty
    {
        get => _loyalty;
        private set => SetLoyalty(value, "direct");
    }

    // ── Identity: Specialization, Ambition, Origin ─────────────────────

    /// <summary>Active specialization. Unlocked via <see cref="TryUnlockSpecialization"/>.</summary>
    [Export]
    public StaffSpecialization Specialization { get; set; } = StaffSpecialization.None;

    /// <summary>What this staff member personally wants out of the arrangement.</summary>
    [Export]
    public StaffAmbition Ambition { get; set; } = StaffAmbition.Money;

    /// <summary>Progress toward <see cref="Ambition"/>, 0–100. At 100 it resolves.</summary>
    [Export(PropertyHint.Range, "0,100,1")]
    public float AmbitionProgress { get; private set; }

    /// <summary>Whether this ambition has already been fulfilled (does not re-fire).</summary>
    [Export]
    public bool AmbitionFulfilled { get; private set; }

    /// <summary>How this staff member was acquired.</summary>
    [Export]
    public StaffOrigin Origin { get; set; } = StaffOrigin.OpenCall;

    /// <summary>
    /// For <see cref="StaffOrigin.Revenge"/> ambitions and poaching grudges —
    /// the syndicate this staff member came from or holds a grudge against.
    /// Empty when not applicable.
    /// </summary>
    [Export]
    public string AssociatedFaction { get; set; } = "";

    /// <summary>
    /// Outstanding debt owed to the house, in dollars. Only non-zero for
    /// <see cref="StaffOrigin.Debt"/>. While positive, the staff member
    /// cannot quit — which is precisely the moral cost of that channel.
    /// </summary>
    [Export]
    public double ContractDebt { get; set; }

    /// <summary>
    /// Affinity toward other staff, keyed by their <see cref="Id"/>.
    /// Range −100 (rivals) to +100 (bonded). Bonded pairs working the same
    /// floor reduce each other's stress; rivals amplify it.
    /// </summary>
    [Export]
    public Godot.Collections.Dictionary<string, float> Relationships { get; set; } = new();

    // ── Derived Properties ─────────────────────────────────────────────

    /// <summary>
    /// Effective maximum Satisfaction, reduced by Trauma.
    /// High-trauma staff can never be fully satisfied.
    /// </summary>
    public float MaxSatisfaction => Mathf.Clamp(100f - (_trauma * 0.4f), 20f, 100f);

    /// <summary>Overall effectiveness rating (composite of all stats).</summary>
    public float EffectivenessRating =>
        (_charisma + _negotiation + _discretion + MaxSatisfaction - _stress) / 400f;

    /// <summary>Whether the staff member is at risk of burning out.</summary>
    public bool IsBurningOut => _stress >= 90f;

    /// <summary>
    /// Whether the staff member wants to walk. Note this is *want*, not
    /// *can* — see <see cref="IsBound"/>. A bound staff member who hits
    /// quit risk does not leave; they become a break and defection risk
    /// instead, which is the whole trade-off of the debt channel.
    /// </summary>
    public bool IsQuitRisk => _satisfaction <= 0f;

    /// <summary>Whether an outstanding contract debt prevents this staff member from leaving.</summary>
    public bool IsBound => ContractDebt > 0.0;

    /// <summary>
    /// Whether this staff member would take a rival's offer or turn on the
    /// house. Low loyalty alone is enough — misery is not required.
    /// </summary>
    public bool IsDefectionRisk => _loyalty <= 20f;

    /// <summary>
    /// Resistance to poaching attempts, 0–1. Blends Loyalty with current
    /// Satisfaction so a happy-but-uncommitted hire is still winnable by rivals.
    /// </summary>
    public float PoachResistance =>
        Mathf.Clamp((_loyalty * 0.7f + _satisfaction * 0.3f) / 100f, 0f, 1f);

    // ── Stat Setters (with clamping and signal emission) ───────────────

    private void SetStat(ref float field, string name, float value)
    {
        var clamped = Mathf.Clamp(value, 0f, 100f);
        if (Mathf.IsEqualApprox(field, clamped)) return;

        var delta = clamped - field;
        field = clamped;
        EmitSignal(SignalName.OnStatChanged, name, field, delta);
    }

    private void SetAgency(ref float field, string name, float value,
        bool checkBurnout = false, bool checkQuit = false, bool checkTrauma = false)
    {
        var clamped = Mathf.Clamp(value, 0f, 100f);
        if (Mathf.IsEqualApprox(field, clamped)) return;

        var delta = clamped - field;
        field = clamped;
        EmitSignal(SignalName.OnAgencyChanged, name, field, delta);

        if (checkBurnout && field >= 90f)
            EmitSignal(SignalName.OnBurnoutRisk, _stress, _satisfaction);

        if (checkQuit && field <= 0f)
            EmitSignal(SignalName.OnQuitRisk, _satisfaction);

        if (checkTrauma && field >= 80f)
            EmitSignal(SignalName.OnTraumaThreshold, _trauma);
    }

    // ── Core Methods: Shift Workload & Stress ──────────────────────────

    /// <summary>
    /// Apply stress from a completed work shift.
    /// Stress scales with workload intensity and inversely with
    /// both the staff member's Discretion stat and the room's
    /// discretion rating.
    /// </summary>
    /// <param name="workload">
    /// Shift intensity, 0–1. 0 = quiet night, 1 = packed house.
    /// </param>
    /// <param name="roomDiscretionRating">
    /// How discreet the assigned room is, 0–100.
    /// Low discretion = high exposure risk = more stress.
    /// </param>
    /// <returns>Actual stress delta applied.</returns>
    public float ApplyShiftWorkload(float workload, float roomDiscretionRating)
    {
        workload = Mathf.Clamp(workload, 0f, 1f);
        roomDiscretionRating = Mathf.Clamp(roomDiscretionRating, 0f, 100f);

        // Base stress: higher workload = more stress
        float baseStress = workload * 25f;

        // Room risk factor: low discretion rooms are stressful
        // A room with 0 discretion = 2.0× multiplier; 100 discretion = 0.5×
        float roomRisk = 1.5f - (roomDiscretionRating / 100f);

        // Staff discretion mitigates stress
        // 100 discretion staff handles risk 2× better than 0 discretion
        float staffMitigation = 1.0f - (_discretion / 200f);

        float stressDelta = baseStress * roomRisk * staffMitigation;

        // Satisfaction erodes with stress — about 40% of stress gain
        float satisfactionLoss = stressDelta * 0.4f;

        Stress += stressDelta;
        Satisfaction -= satisfactionLoss;

        GD.Print($"[Staff:{StaffName}] Shift complete: workload={workload:F2} " +
                 $"roomDisc={roomDiscretionRating:F0} → " +
                 $"Stress +{stressDelta:F1} (now {_stress:F1}), " +
                 $"Satisfaction -{satisfactionLoss:F1} (now {_satisfaction:F1})");

        // Clamp satisfaction to trauma-adjusted max
        if (_satisfaction > MaxSatisfaction)
            Satisfaction = MaxSatisfaction;

        return stressDelta;
    }

    /// <summary>
    /// Apply stress from a specific traumatic event (raid, violent
    /// incident, client confrontation). Bypasses the normal workload
    /// formula and can directly increase Trauma.
    /// </summary>
    /// <param name="baseStress">Immediate stress increase.</param>
    /// <param name="traumaIntensity">
    /// How traumatic the event was, 0–1. Portion of stress converted to Trauma.
    /// </param>
    public void ApplyTraumaticEvent(float baseStress, float traumaIntensity)
    {
        traumaIntensity = Mathf.Clamp(traumaIntensity, 0f, 1f);
        baseStress = Mathf.Max(0f, baseStress);

        float traumaGain = baseStress * traumaIntensity * 0.5f;
        float actualStress = baseStress * (1f - traumaIntensity * 0.3f);

        Stress += actualStress;
        Trauma += traumaGain;
        Satisfaction -= baseStress * 0.2f;

        GD.Print($"[Staff:{StaffName}] Traumatic event: " +
                 $"Stress +{actualStress:F1} Trauma +{traumaGain:F1} " +
                 $"(now Stress={_stress:F1} Trauma={_trauma:F1})");
    }

    // ── Recovery & Morale Methods ──────────────────────────────────────

    /// <summary>
    /// Rest for a number of hours. Reduces stress and slightly
    /// restores satisfaction.
    /// </summary>
    /// <param name="hours">Hours of rest (max effective: 12).</param>
    public void Rest(float hours)
    {
        hours = Mathf.Clamp(hours, 0f, 12f);

        float stressReduction = hours * 3.5f;
        float satisfactionGain = hours * 0.8f;

        Stress -= stressReduction;
        Satisfaction += satisfactionGain;

        if (_satisfaction > MaxSatisfaction)
            Satisfaction = MaxSatisfaction;

        GD.Print($"[Staff:{StaffName}] Rested {hours:F1}h → " +
                 $"Stress -{stressReduction:F1} Satisfaction +{satisfactionGain:F1}");
    }

    /// <summary>
    /// Receive a cash bonus. Boosts satisfaction proportional
    /// to the bonus relative to salary.
    /// </summary>
    /// <param name="amount">Bonus amount in dollars.</param>
    public void ReceiveBonus(double amount)
    {
        if (amount <= 0) return;

        // Satisfaction boost: bigger relative to salary = bigger boost
        float boost = Mathf.Clamp((float)(amount / Salary) * 8f, 1f, 25f);
        Satisfaction += boost;

        if (_satisfaction > MaxSatisfaction)
            Satisfaction = MaxSatisfaction;

        GD.Print($"[Staff:{StaffName}] Bonus ${amount:F2} → Satisfaction +{boost:F1} (now {_satisfaction:F1})");
    }

    // ── Stat Training ──────────────────────────────────────────────────

    /// <summary>
    /// Apply training to improve an RPG stat. Gains diminish as
    /// the stat approaches 100.
    /// </summary>
    /// <param name="statName">"Charisma", "Negotiation", or "Discretion".</param>
    /// <param name="hours">Training hours invested.</param>
    /// <returns>Actual stat gain achieved.</returns>
    public float Train(string statName, float hours)
    {
        hours = Mathf.Clamp(hours, 0f, 20f);

        float currentValue = statName switch
        {
            "Charisma" => _charisma,
            "Negotiation" => _negotiation,
            "Discretion" => _discretion,
            _ => throw new ArgumentException($"Unknown stat: {statName}")
        };

        // Diminishing returns as stat approaches 100
        float gainMultiplier = 1.0f - (currentValue / 120f);
        float gain = hours * 1.2f * gainMultiplier;

        switch (statName)
        {
            case "Charisma": Charisma += gain; break;
            case "Negotiation": Negotiation += gain; break;
            case "Discretion": Discretion += gain; break;
        }

        GD.Print($"[Staff:{StaffName}] Trained {statName} for {hours:F1}h → +{gain:F1}");
        return gain;
    }

    // ── Therapy / Trauma Recovery ──────────────────────────────────────

    /// <summary>
    /// Send staff to therapy. Reduces Trauma over time.
    /// More expensive therapy is more effective.
    /// </summary>
    /// <param name="sessionCost">Cost of the therapy session.</param>
    /// <returns>Trauma reduction achieved.</returns>
    public float AttendTherapy(double sessionCost)
    {
        if (sessionCost <= 0) return 0f;

        float reduction = Mathf.Clamp((float)(sessionCost / 30.0), 1f, 15f);
        Trauma -= reduction;

        GD.Print($"[Staff:{StaffName}] Therapy (${sessionCost:F0}) → Trauma -{reduction:F1} (now {_trauma:F1})");
        return reduction;
    }

    // ── Loyalty ────────────────────────────────────────────────────────

    /// <summary>
    /// Adjust Loyalty by a delta. Always route changes through here rather
    /// than assigning, so the reason string reaches the UI and the defection
    /// signal fires exactly once on the downward crossing.
    /// </summary>
    /// <param name="delta">Change to apply. Negative erodes loyalty.</param>
    /// <param name="reason">Short cause, surfaced in the staff profile log.</param>
    public void AdjustLoyalty(float delta, string reason = "unspecified")
    {
        if (Mathf.IsZeroApprox(delta)) return;
        SetLoyalty(_loyalty + delta, reason);
    }

    private void SetLoyalty(float value, string reason)
    {
        var clamped = Mathf.Clamp(value, 0f, 100f);
        if (Mathf.IsEqualApprox(_loyalty, clamped)) return;

        var wasDefectionRisk = _loyalty <= 20f;
        var delta = clamped - _loyalty;
        _loyalty = clamped;

        EmitSignal(SignalName.OnLoyaltyChanged, _loyalty, delta, reason);

        // Only fire on the crossing, not on every point below the line.
        if (!wasDefectionRisk && _loyalty <= 20f)
            EmitSignal(SignalName.OnDefectionRisk, Id, _loyalty);
    }

    // ── Ambition ───────────────────────────────────────────────────────

    /// <summary>
    /// Advance progress toward this staff member's ambition. Progress also
    /// feeds Loyalty directly — pursuing what they want is the primary way
    /// the house earns commitment.
    /// </summary>
    /// <param name="progress">Points of progress, 0–100 scale.</param>
    /// <returns>True if this call fulfilled the ambition.</returns>
    public bool AdvanceAmbition(float progress)
    {
        if (AmbitionFulfilled || progress <= 0f) return false;

        AmbitionProgress = Mathf.Clamp(AmbitionProgress + progress, 0f, 100f);
        AdjustLoyalty(progress * 0.35f, $"ambition:{Ambition}");

        EmitSignal(SignalName.OnAmbitionProgressed, Id, (int)Ambition, AmbitionProgress);

        if (AmbitionProgress < 100f) return false;

        AmbitionFulfilled = true;
        AdjustLoyalty(20f, $"ambition fulfilled:{Ambition}");
        EmitSignal(SignalName.OnAmbitionFulfilled, Id, (int)Ambition);

        GD.Print($"[Staff:{StaffName}] Ambition fulfilled: {Ambition}.");
        return true;
    }

    /// <summary>
    /// Erode loyalty because the house has done nothing toward this staff
    /// member's ambition. Called on the weekly review, not per night —
    /// neglect should be a slow burn the player can notice and correct.
    /// </summary>
    public void ApplyAmbitionNeglect()
    {
        if (AmbitionFulfilled) return;
        AdjustLoyalty(-3f, $"neglected:{Ambition}");
    }

    // ── Specialization ─────────────────────────────────────────────────

    /// <summary>Whether current stats qualify for a given specialization.</summary>
    public bool CanSpecializeAs(StaffSpecialization spec) => spec switch
    {
        StaffSpecialization.None => true,
        StaffSpecialization.Hostess => _charisma >= 60f,
        StaffSpecialization.Negotiator => _negotiation >= 60f,
        StaffSpecialization.Fixer => _discretion >= 65f,
        StaffSpecialization.Informant => _discretion >= 55f,
        StaffSpecialization.Matron => _charisma >= 50f && _negotiation >= 50f && _discretion >= 50f,
        _ => false
    };

    /// <summary>
    /// Commit to a specialization. Requires the stat threshold and that no
    /// specialization is already set — this is a deliberate one-time choice,
    /// so training toward a second path has a real opportunity cost.
    /// </summary>
    /// <returns>True if the specialization was applied.</returns>
    public bool TryUnlockSpecialization(StaffSpecialization spec)
    {
        if (spec == StaffSpecialization.None) return false;
        if (Specialization != StaffSpecialization.None) return false;
        if (!CanSpecializeAs(spec)) return false;

        Specialization = spec;
        AdjustLoyalty(5f, $"specialized:{spec}");
        EmitSignal(SignalName.OnSpecializationUnlocked, Id, (int)spec);

        GD.Print($"[Staff:{StaffName}] Specialized as {spec}.");
        return true;
    }

    /// <summary>Every specialization this staff member currently qualifies for.</summary>
    public System.Collections.Generic.List<StaffSpecialization> GetEligibleSpecializations()
    {
        var eligible = new System.Collections.Generic.List<StaffSpecialization>();
        foreach (StaffSpecialization spec in Enum.GetValues<StaffSpecialization>())
        {
            if (spec == StaffSpecialization.None) continue;
            if (CanSpecializeAs(spec)) eligible.Add(spec);
        }
        return eligible;
    }

    // ── Relationships ──────────────────────────────────────────────────

    /// <summary>Affinity toward another staff member, −100 to +100. Zero if unknown.</summary>
    public float GetRelationship(string otherId)
    {
        if (string.IsNullOrEmpty(otherId)) return 0f;
        return Relationships.TryGetValue(otherId, out var value) ? value : 0f;
    }

    /// <summary>
    /// Adjust affinity toward another staff member. Note this sets one
    /// direction only — <see cref="StaffRoster"/> owns making bonds mutual,
    /// because one-sided attachment is a story the roster should be able to tell.
    /// </summary>
    public void AdjustRelationship(string otherId, float delta)
    {
        if (string.IsNullOrEmpty(otherId) || otherId == Id) return;

        var current = GetRelationship(otherId);
        Relationships[otherId] = Mathf.Clamp(current + delta, -100f, 100f);
    }

    /// <summary>Whether affinity toward the other staff member counts as a bond.</summary>
    public bool IsBondedWith(string otherId) => GetRelationship(otherId) >= 40f;

    /// <summary>Whether affinity toward the other staff member counts as a rivalry.</summary>
    public bool IsRivalOf(string otherId) => GetRelationship(otherId) <= -40f;

    // ── Persistence ────────────────────────────────────────────────────

    /// <summary>
    /// Restore Loyalty from a save without firing change or defection
    /// signals. Loading is not a gameplay event — emitting here would make
    /// every load look like a fresh crisis to any connected listener.
    /// </summary>
    public void RestoreLoyalty(float value) => _loyalty = Mathf.Clamp(value, 0f, 100f);

    /// <summary>Restore ambition state from a save without firing signals.</summary>
    public void RestoreAmbitionProgress(float progress, bool fulfilled)
    {
        AmbitionProgress = Mathf.Clamp(progress, 0f, 100f);
        AmbitionFulfilled = fulfilled;
    }

    // ── Utility ────────────────────────────────────────────────────────

    /// <summary>Reset all agency variables to default values.</summary>
    public void ResetAgency()
    {
        _stress = 0f;
        _satisfaction = 70f;
        _trauma = 0f;
        _loyalty = 50f;
        GD.Print($"[Staff:{StaffName}] Agency variables reset.");
    }

    /// <summary>Generate a quick summary string for UI display.</summary>
    public string GetSummary()
    {
        var spec = Specialization == StaffSpecialization.None ? Role : Specialization.ToString();
        return $"{StaffName} ({spec}) | " +
               $"Cha:{_charisma:F0} Neg:{_negotiation:F0} Dis:{_discretion:F0} | " +
               $"Stress:{_stress:F0} Sat:{_satisfaction:F0} Loy:{_loyalty:F0} " +
               $"Trauma:{_trauma:F0}" +
               $"{(IsBurningOut ? " ⚠BURN" : "")}" +
               $"{(IsQuitRisk ? (IsBound ? " ⚠BOUND" : " ⚠QUIT") : "")}" +
               $"{(IsDefectionRisk ? " ⚠DEFECT" : "")}";
    }

    public override string ToString() => GetSummary();
}
